--------------------------------------------------------
--  Fichier créé - dimanche-décembre-12-2021   
--------------------------------------------------------
DROP TABLE "COFFA"."GUICHET";
DROP TABLE "COFFA"."TICKET";
DROP TABLE "COFFA"."GS_PERSONNELS";
DROP TABLE "COFFA"."ANIMAL";
DROP TABLE "COFFA"."CLIENT";
DROP TABLE "COFFA"."ACHAT";
--------------------------------------------------------
--  DDL for Table GUICHET
--------------------------------------------------------

  CREATE TABLE "COFFA"."GUICHET" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"CATEGORIE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "COFFA"."TICKET" 
   (	"ID" NUMBER, 
	"QUANTITE" NUMBER, 
	"PRIX" NUMBER, 
	"GUICHET_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GS_PERSONNELS
--------------------------------------------------------

  CREATE TABLE "COFFA"."GS_PERSONNELS" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" DATE, 
	"AGE" NUMBER, 
	"TELEPHONE" NUMBER, 
	"VILLE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"CIN_ADMIN" NUMBER, 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ANIMAL
--------------------------------------------------------

  CREATE TABLE "COFFA"."ANIMAL" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"CLASSE" VARCHAR2(20 BYTE), 
	"DATE_AJOUT" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "COFFA"."CLIENT" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"DATEDENAISSANCE" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(1 BYTE), 
	"NUMTEL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ACHAT
--------------------------------------------------------

  CREATE TABLE "COFFA"."ACHAT" 
   (	"ID" NUMBER, 
	"TICKET_ID" NUMBER, 
	"QUANTITE" NUMBER, 
	"PERSONNE_ID" NUMBER, 
	"ETAT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into COFFA.GUICHET
SET DEFINE OFF;
Insert into COFFA.GUICHET (ID,NOM,DESCRIPTION,CATEGORIE) values ('3','hhhjkqiwo','bbhekjk','INDIVIDUEL');
Insert into COFFA.GUICHET (ID,NOM,DESCRIPTION,CATEGORIE) values ('5','ghwke','kkkdh','COUPLE');
Insert into COFFA.GUICHET (ID,NOM,DESCRIPTION,CATEGORIE) values ('12','raoud','no money','INDIVIDUEL');
REM INSERTING into COFFA.TICKET
SET DEFINE OFF;
REM INSERTING into COFFA.GS_PERSONNELS
SET DEFINE OFF;
Insert into COFFA.GS_PERSONNELS (CIN,NOM,PRENOM,DATE_NAISSANCE,AGE,TELEPHONE,VILLE,ADRESSE,CIN_ADMIN,PASSWORD,USERNAME) values ('2','onana','miguel',to_date('01/01/00','DD/MM/RR'),'21','78945612','yde','yde','2','789456','stephane');
Insert into COFFA.GS_PERSONNELS (CIN,NOM,PRENOM,DATE_NAISSANCE,AGE,TELEPHONE,VILLE,ADRESSE,CIN_ADMIN,PASSWORD,USERNAME) values ('789','clavel','djaneng',to_date('01/01/00','DD/MM/RR'),'21','7989654','yde','yde','789',null,null);
Insert into COFFA.GS_PERSONNELS (CIN,NOM,PRENOM,DATE_NAISSANCE,AGE,TELEPHONE,VILLE,ADRESSE,CIN_ADMIN,PASSWORD,USERNAME) values ('123','adrien','adrien',to_date('01/01/00','DD/MM/RR'),'21','78965412','tunis','tunis',null,null,null);
REM INSERTING into COFFA.ANIMAL
SET DEFINE OFF;
Insert into COFFA.ANIMAL (ID,NOM,CLASSE,DATE_AJOUT,SEXE) values ('111','lion','carni','2021/12/07','M');
Insert into COFFA.ANIMAL (ID,NOM,CLASSE,DATE_AJOUT,SEXE) values ('2222','chien','carnivor','2021/12/07','F');
REM INSERTING into COFFA.CLIENT
SET DEFINE OFF;
REM INSERTING into COFFA.ACHAT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index GUICHET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFA"."GUICHET_PK" ON "COFFA"."GUICHET" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GUICHET_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFA"."GUICHET_U" ON "COFFA"."GUICHET" ("NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFA"."TICKET_PK" ON "COFFA"."TICKET" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GS_PERSONNELS_U
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFA"."GS_PERSONNELS_U" ON "COFFA"."GS_PERSONNELS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PERSONNELS
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFA"."PK_PERSONNELS" ON "COFFA"."GS_PERSONNELS" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ANIMAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFA"."ANIMAL_PK" ON "COFFA"."ANIMAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFA"."CLIENT_PK" ON "COFFA"."CLIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_U_01
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFA"."CLIENT_U_01" ON "COFFA"."CLIENT" ("NUMTEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACHAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COFFA"."ACHAT_PK" ON "COFFA"."ACHAT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GUICHET
--------------------------------------------------------

  ALTER TABLE "COFFA"."GUICHET" ADD CONSTRAINT "GUICHET_U" UNIQUE ("NOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COFFA"."GUICHET" MODIFY ("CATEGORIE" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."GUICHET" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."GUICHET" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."GUICHET" ADD CONSTRAINT "GUICHET_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COFFA"."GUICHET" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "COFFA"."TICKET" MODIFY ("GUICHET_ID" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."TICKET" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."TICKET" MODIFY ("QUANTITE" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."TICKET" ADD CONSTRAINT "TICKET_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COFFA"."TICKET" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GS_PERSONNELS
--------------------------------------------------------

  ALTER TABLE "COFFA"."GS_PERSONNELS" ADD CONSTRAINT "GS_PERSONNELS_U" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COFFA"."GS_PERSONNELS" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."GS_PERSONNELS" ADD CONSTRAINT "PK_PERSONNELS" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COFFA"."GS_PERSONNELS" MODIFY ("TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."GS_PERSONNELS" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."GS_PERSONNELS" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."GS_PERSONNELS" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANIMAL
--------------------------------------------------------

  ALTER TABLE "COFFA"."ANIMAL" MODIFY ("SEXE" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."ANIMAL" MODIFY ("DATE_AJOUT" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."ANIMAL" MODIFY ("CLASSE" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."ANIMAL" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."ANIMAL" ADD CONSTRAINT "ANIMAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COFFA"."ANIMAL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "COFFA"."CLIENT" ADD CONSTRAINT "CLIENT_U_01" UNIQUE ("NUMTEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COFFA"."CLIENT" MODIFY ("SEXE" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."CLIENT" MODIFY ("DATEDENAISSANCE" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."CLIENT" MODIFY ("NUMTEL" NOT NULL ENABLE);
  ALTER TABLE "COFFA"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COFFA"."CLIENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACHAT
--------------------------------------------------------

  ALTER TABLE "COFFA"."ACHAT" ADD CONSTRAINT "ACHAT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COFFA"."ACHAT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "COFFA"."TICKET" ADD CONSTRAINT "TICKET_FK" FOREIGN KEY ("GUICHET_ID")
	  REFERENCES "COFFA"."GUICHET" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GS_PERSONNELS
--------------------------------------------------------

  ALTER TABLE "COFFA"."GS_PERSONNELS" ADD CONSTRAINT "FK_PERSONNELS" FOREIGN KEY ("CIN_ADMIN")
	  REFERENCES "COFFA"."GS_PERSONNELS" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACHAT
--------------------------------------------------------

  ALTER TABLE "COFFA"."ACHAT" ADD CONSTRAINT "ACHAT_FK" FOREIGN KEY ("TICKET_ID")
	  REFERENCES "COFFA"."TICKET" ("ID") ENABLE;
  ALTER TABLE "COFFA"."ACHAT" ADD CONSTRAINT "ACHAT_FK_02" FOREIGN KEY ("PERSONNE_ID")
	  REFERENCES "COFFA"."CLIENT" ("CIN") ENABLE;
